language: python
python:
      - "2.7"

before_install:
      - pip install --upgrade pip

install:
      - pip install autopep8
      - pip install coverage
      - pip install numpy
      - pip install pylint
      - pip install BeautifulSoup4
before_script:
      - uname -a
      - printenv | sort

script:
      - make test 


